[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "vv"
version = "2.0.0"
description = "verification and validation for OpenModel"
readme = "README.MD"
requires-python = ">=3.8"
authors = [{name = "Owain Beynon", email = "o.beynon@ucl.ac.uk"}]
classifiers = [
     "Development Status :: 4 - Beta",
     "Programming Language :: Python"
]

dependencies = [
    "numpy",
    "matplotlib",
    "scikit-learn",
    "ipywidgets",
    "nonconformist",
    "omikb",
    "discomat",
    # GitHub-hosted dependency
    "discomat @ git+https://github.com/materials-discovery/discomat.git"
]

[project.optional-dependencies]

[project.urls]
repository = "https://github.com/H2020-OpenModel/OMI-VV/"

# Explicitly specify the package directories
[tool.setuptools]
packages = ["vv"]  # or ["find:vv", "find:images"] if both are needed

